name: Update Submodule Pointer

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository with full history and submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Reset to latest origin/main to avoid divergence
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Update submodule pointer
        run: git submodule update --remote

      - name: Stage submodule changes
        run: git add .

      - name: Commit submodule pointer changes if any
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update submodule pointer to latest commit from aisgraph"
          else
            echo "No submodule updates detected."
            exit 0
          fi

      - name: Push changes to remote
        run: git push origin HEAD:main --force-with-lease
