name: Update Submodule Pointer

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Update submodule
        run: |
          # Initialize and update submodule
          git submodule update --init
          
          # Update submodule to latest commit
          git submodule update --remote
          
          # If there are changes, commit and push them
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "chore: Update aisgraph submodule to latest commit"
            git pull --rebase origin ${{ github.event.repository.default_branch }}
            git push origin ${{ github.event.repository.default_branch }}
          else
            echo "No changes to commit"
          fi
