name: Update Submodule Pointer

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update submodule
        run: |
          # Ensure we're on the right branch
          git checkout ${{ github.event.repository.default_branch }}
          
          # Get the latest changes
          git fetch origin
          git reset --hard origin/${{ github.event.repository.default_branch }}
          
          # Update the submodule
          git submodule update --init --recursive
          git submodule update --remote --recursive
          
          # Check for changes and commit them
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "chore: Update aisgraph submodule to latest commit"
            
            # Force push with lease ensures the push succeeds while still being safe
            # It will only push if the remote hasn't changed from what we expect
            git push --force-with-lease origin ${{ github.event.repository.default_branch }}
          else
            echo "No changes to commit"
          fi
