name: Update Submodule Pointer

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository with submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Update submodule pointer
        run: git submodule update --remote

      - name: Pull latest changes from remote
        run: git pull --rebase origin ${{ github.event.repository.default_branch }}

      - name: Commit and push submodule pointer changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Update submodule pointer to latest commit from aisgraph"
            git push origin HEAD:${{ github.event.repository.default_branch }}
          else
            echo "No submodule updates detected."
