name: Update Submodule Pointer

on:
  repository_dispatch:
    types: [submodule-updated]

concurrency:
  group: update-submodule
  cancel-in-progress: true

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAIN_REPO_PAT }}
          submodules: recursive
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.MAIN_REPO_PAT }}@github.com/ai-safety-graph/AISafetyGraph.git

      - name: Update submodule to latest commit
        run: |
          git fetch --prune
          git reset --hard origin/main
          git submodule update --init --remote --force

      - name: Commit and Push changes if submodule updated
        run: |
          if [[ $(git status --porcelain aisgraph) ]]; then
            git add aisgraph
            git commit -m "Update submodule pointer to $(git -C aisgraph rev-parse --short HEAD)"
            git pull --rebase origin main
            git push origin HEAD:main --force-with-lease
          else
            echo "No submodule changes detected."
          fi
